name: lint

on:
  push:
    branches: '**'
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    runs-on: ubuntu-latest
    env:
      LLVM_VERSION: 20
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format-${{ env.LLVM_VERSION }}
        run: |
          sudo chmod +x ./scripts/install_clang_format.sh
          sudo ./scripts/install_clang_format.sh ${{ env.LLVM_VERSION }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependency
        run: pip install pre-commit==4.0.1
      - name: Install pre-commit
        run: pre-commit install
      - name: Run pre-commit
        run: pre-commit run --all-files
