name: sphinx deploy
on:
  push:
    branches:
      - dev
permissions:
  contents: write
jobs:
  deploy:
    runs-on: [self-hosted, integration]
    container:
      image: registry.cn-sh-01.sensecore.cn/sandai-ccr/magi-base:25.02.6
      options: --gpus all --ipc host
      credentials:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      env:
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTP_PROXY }}
        http_proxy_cn: ${{ secrets.HTTP_PROXY_CN }}
        https_proxy_cn: ${{ secrets.HTTP_PROXY_CN }}
        WANDB_ENTITY: ${{ secrets.WANDB_ENTITY }}
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        GITHUB_SHA: ${{ github.sha }}
    steps:
      - name: echo proxy
        run: |
          echo "http_proxy: $http_proxy"
          echo "https_proxy: $https_proxy"
          echo "secret.HTTP_PROXY: ${{ secrets.HTTP_PROXY }}"
          echo "secret.HTTPS_PROXY: ${{ secrets.HTTP_PROXY }}"
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y rsync
          pip install sphinx
          pip install pydata-sphinx-theme myst_parser sphinx-copybutton
      - name: Build docs
        run: |
          cd docs
          make clean
          sphinx-build -b html source/ html/
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.event_name == 'push' }}
        with:
          branch: gh-pages
          folder: docs/html
          target-folder: docs
