name: sphinx deploy
on:
  push:
    branches:
      - dev
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: nvcr.io/nvidia/pytorch:25.02-py3
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y rsync
          pip install sphinx
          pip install pydata-sphinx-theme myst_parser sphinx-copybutton
          git config --global --add safe.directory /__w/MagiAttention/MagiAttention
          git submodule update --init --recursive
          pip install -e . -v --no-build-isolation
      - name: Build docs
        run: |
          cd docs
          make clean
          sphinx-build -b html source/ html/
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.event_name == 'push' }}
        with:
          branch: gh-pages
          folder: docs/html
          target-folder: docs/v1.0.3
