name: sphinx deploy
on:
  push:
    branches:
      - dev
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
<<<<<<< HEAD
=======
      - name: Install dependencies
        run: |
          pip install sphinx
          pip install pydata-sphinx-theme myst_parser
      - name: Build docs
        run: |
          cd docs
          make clean
          make html
>>>>>>> origin/dev
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.event_name == 'push' }}
        with:
          branch: gh-pages
<<<<<<< HEAD
          folder: docs/html
=======
          folder: docs/build/html
>>>>>>> origin/dev
          target-folder: docs
