name: sphinx deploy
on:
  push:
    branches:
      - docs
permissions:
  contents: write
jobs:
  deploy:
    runs-on: [self-hosted]
    container:
      image: nvcr.io/nvidia/pytorch:25.02-py3
      options: --gpus all --ipc host
      env:
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTP_PROXY }}
        http_proxy_cn: ${{ secrets.HTTP_PROXY_CN }}
        https_proxy_cn: ${{ secrets.HTTP_PROXY_CN }}
        GITHUB_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get install rsync
          pip install sphinx
          pip install pydata-sphinx-theme myst_parser
      - name: Build docs
        run: |
          cd docs
          make clean
          sphinx-build -b html source/ html/
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.event_name == 'push' }}
        with:
          branch: gh-pages
          folder: docs/html
          target-folder: docs
